---
- name: Test Ansible on local machine
  hosts: all
  connection: local
  gather_facts: no

  tasks:
    - name: Print Hello World
      debug:
        msg: "Hello, Ansible is working on {{ inventory_hostname }}"
