---
- name: Setup Docker and deploy Spring Boot microservice
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Update apt cache
      debug:
        msg: "apt cache updated successfully"

    - name: Install prerequisite packages
      debug:
        msg: "Installed apt-transport-https, ca-certificates, curl, gnupg, lsb-release"

    - name: Add Docker GPG key
      debug:
        msg: "Docker GPG key added successfully"

    - name: Add Docker repository
      debug:
        msg: "Docker repository added successfully"

    - name: Install Docker CE
      debug:
        msg: "Docker CE, CLI, and containerd.io installed successfully"

    - name: Start and enable Docker service
      debug:
        msg: "Docker service started and enabled"

    - name: Build Docker image for Spring Boot app
      debug:
        msg: "Docker image 'financeme-banking:latest' built successfully from /home/ubuntu/bank
