---
- name: Configure Docker and deploy banking app container
  hosts: all
  become: true
  vars:
    DOCKER_IMAGE: finance-me
    DOCKER_TAG: "1.0"
    APP_PORT_HOST: "8084"
    APP_PORT_CONTAINER: "8081"
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages for Docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Install Docker using official convenience script
      shell: curl -fsSL https://get.docker.com | sh
      args:
        executable: /bin/bash

    - name: Ensure Docker service is running
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Remove old Docker container if exists
      docker_container:
        name: "{{ DOCKER_IMAGE }}"
        state: absent
      ignore_errors: yes

    - name: Build Docker image from local code
      docker_image:
        name: "{{ DOCKER_IMAGE }}"
        tag: "{{ DOCKER_TAG }}"
        build:
          path: "{{ playbook_dir }}"
        source: build

    - name: Run banking app container
      docker_container:
        name: "{{ DOCKER_IMAGE }}"
        image: "{{ DOCKER_IMAGE }}:{{ DOCKER_TAG }}"
        state: started
        restart_policy: always
        published_ports:
          - "{{ APP_PORT_HOST }}:{{ APP_PORT_CONTAINER }}"
