---
- name: Configure Docker and deploy banking app container on EC2
  hosts: all
  become: true
  connection: local

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker from Ubuntu repo
      apt:
        name: docker.io
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Remove old Docker container if exists
      command: docker rm -f finance-me
      ignore_errors: yes

    - name: Build Docker image from local code
      docker_image:
        path: .
        name: finance-me
        tag: "1.0"
        state: present

    - name: Run banking app container
      docker_container:
        name: finance-me
        image: finance-me:1.0
        state: started
        restart_policy: always
        published_ports:
          - "8084:8081"
