---
- name: Deploy FinanceMe Banking App
  hosts: localhost
  connection: local
  become: true

  vars:
    app_url: "{{ app_url | default('http://localhost:8081') }}"

  tasks:
    - name: Ensure prerequisites are installed
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Install Docker via convenience script
      ansible.builtin.shell: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh
      args:
        creates: /usr/bin/docker

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Remove old container if exists
      command: docker rm -f finance-me
      ignore_errors: yes

    - name: Build Docker image from app code
      community.docker.docker_image:
        name: finance-me
        tag: "1.0"
        build:
          path: "{{ playbook_dir }}"
        source: build

    - name: Run FinanceMe container
      community.docker.docker_container:
        name: finance-me
        image: finance-me:1.0
        state: started
        restart_policy: always
        published_ports:
          - "8084:8081"

    - name: Verify container is running
      command: docker ps --filter "name=finance-me"
      register: docker_status

    - debug:
        msg: "{{ docker_status.stdout }}"
