---
- name: Configure Docker and deploy banking app container on EC2
  hosts: all
  become: true
  connection: ssh

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages for Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
        state: present

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Update apt cache after adding Docker repo
      apt:
        update_cache: yes

    - name: Install Docker CE
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Ensure Docker service is running
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Remove old Docker container if exists
      docker_container:
        name: finance-me
        state: absent
      ignore_errors: yes

    - name: Pull Docker image finance-me:1.0
      docker_image:
        name: vedika/finance-me
        tag: "1.0"
        source: pull

    - name: Run banking app container
      docker_container:
        name: finance-me
        image: vedika/finance-me:1.0
        state: started
        restart_policy: always
        published_ports:
          - "8084:8081"
