---
- name: Deploy FinanceMe Banking App
  hosts: localhost
  connection: local
  become: true

  vars:
    target_env: "{{ target_env | default('local') }}"
    app_url: "{{ app_url | default('http://localhost:8081') }}"

  tasks:
    - name: Ensure prerequisites are installed
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Ensure /etc/apt/keyrings directory exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Remove existing Docker repo file to prevent conflicts
      file:
        path: /etc/apt/sources.list.d/docker.list
        state: absent

    - name: Add Docker GPG key
      ansible.builtin.shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Add Docker repo
      copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: |
          deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        mode: '0644'

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Remove old container if exists
      command: docker rm -f finance-me
      ignore_errors: yes

    - name: Build Docker image from app code
      community.docker.docker_image:
        name: finance-me
        tag: "1.0"
        build:
          path: "{{ playbook_dir }}"
        source: build

    - name: Run FinanceMe container
      community.docker.docker_container:
        name: finance-me
        image: finance-me:1.0
        state: started
        restart_policy: always
        published_ports:
          - "8081:8081"

    - name: Verify container is running
      command: docker ps --filter "name=finance-me"
      register: docker_status

    - debug:
        msg: "{{ docker_status.stdout }}"
