---
- name: Configure Docker and deploy banking app container
  hosts: all
  become: true
  connection: local

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Remove conflicting containerd (if present)
      apt:
        name: containerd
        state: absent
      ignore_errors: yes

    - name: Install Docker using official script
      shell: curl -fsSL https://get.docker.com | sh
      args:
        executable: /bin/bash

    - name: Ensure Docker service is running
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add current user to docker group
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes

    - name: Remove old container if exists
      command: docker rm -f finance-me
      ignore_errors: yes

    - name: Build Docker image from local code
      docker_image:
        name: finance-me
        tag: "1.0"
        build:
          path: .
        source: build
        state: present

    - name: Run banking app container
      docker_container:
        name: finance-me
        image: finance-me:1.0
        state: started
        restart_policy: always
        published_ports:
          - "8084:8081"

    - name: Verify container is running
      command: docker ps --filter "name=finance-me" --format "{{.Names}}: {{.Status}}"
      register: docker_status

    - name: Show container status
      debug:
        msg: "{{ docker_status.stdout }}"
