---
- name: Configure Docker and deploy banking app container
  hosts: localhost
  become: true
  connection: local

  vars:
    app_name: finance-me
    app_port: 8081
    docker_image: financeme-banking:latest
    jar_file: target/banking-0.0.1-SNAPSHOT.jar

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages for Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker apt repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker Engine
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Remove old Docker container if exists
      docker_container:
        name: "{{ app_name }}"
        state: absent
        force_kill: yes

    - name: Build Docker image from local jar
      docker_image:
        path: .
        name: "{{ docker_image.split(':')[0] }}"
        tag: "{{ docker_image.split(':')[1] }}"
        buildargs:
          JAR_FILE: "{{ jar_file }}"
        force: yes

    - name: Run banking app container
      docker_container:
        name: "{{ app_name }}"
        image: "{{ docker_image }}"
        state: started
        restart_policy: always
        published_ports:
          - "{{ app_port }}:8081"
